language: cpp

compiler:
  - clang
  # - gcc

before_install:
  # Always install g++4.9.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

  - sudo apt-get update -qq

install: 
  # cmake
  - sudo apt-get install cmake

  # Always install g++4.8.1
  - sudo apt-get install -qq g++-4.9
  - sudo apt-get install -qq g++-4.9-multilib
  - if [ "$CXX" = "g++" ]; then export CMAKE_CXX_COMPILER="g++-4.9"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  
  # clang 3.4
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
  - if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-std=c++11 -stdlib=libc++"; fi
  - if [ "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi

  - if [ "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
  - if [ "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
  - if [ "$CXX" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
  - if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
  - if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi

  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.4"; fi

script:
  # - mkdir build 
  - cd build 
  - cmake .
  - make

after_script:
  - ./zupply_sample
  # - ctest .
  # - make valgrind

branches:
  only:
    - master